# Generated by Django 3.1.3 on 2020-12-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0002_auto_20201129_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='designer_id',
        ),
        migrations.AddField(
            model_name='game',
            name='designer',
            field=models.CharField(default='', max_length=75),
        ),
    ]
