# Generated by Django 3.1.3 on 2020-12-02 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0004_auto_20201202_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', related_query_name='review', to='raterprojectapi.player'),
        ),
    ]
