# Generated by Django 3.1.3 on 2020-12-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0005_auto_20201202_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='player_id',
            new_name='player',
        ),
    ]
