# Generated by Django 3.1.3 on 2021-01-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0007_auto_20210121_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(related_name='categories', related_query_name='category', to='raterprojectapi.Category'),
        ),
    ]
