# Generated by Django 3.1.3 on 2021-01-22 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0009_auto_20210122_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_image',
        ),
        migrations.AddField(
            model_name='game',
            name='action_pic',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.CreateModel(
            name='GamePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_pic', models.ImageField(null=True, upload_to='actionimages')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pictures', to='raterprojectapi.game')),
            ],
        ),
    ]
