# Generated by Django 3.1.3 on 2021-01-22 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0010_auto_20210122_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='action_pic',
        ),
    ]
