# Generated by Django 3.1.3 on 2021-01-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0012_auto_20210123_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='categories', related_query_name='category', to='raterprojectapi.Categories'),
        ),
    ]
